name: hello-world
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Hello, World!"

  second-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print
        run: echo "job second"



